### ISSUE TITLE
Security Rule Type

### ISSUE THREAD

**Issue by zucoa** [eapowertools/qs-security-rule-analyzer#1]
@danielpilla - once again, you're pulling together great and super helpful tools. Would you be able to add filter capability to distinguish data connection versus stream related rules? (Wildcard searches on SecurityRuleResourceFilter are helpful, just looking for something pared down a bit.)

**Comment by danielpilla** [comment]
@zucoa - apologies for just seeing this! I've updated the application accordingly to support this feature. Thanks for the input, and good idea! https://github.com/eapowertools/qs-security-rule-analyzer/releases
